import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, ChevronDown, Menu, Minus, Plus, Search, ShoppingBag, X } from 'lucide-react'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import './styles.css'

gsap.registerPlugin(ScrollTrigger)

const products = [
  { id: 1, name: 'Ritual Bath Set', category: 'Bath & body', price: 1499, tone: 'sand', description: 'A calm, considered set for your daily reset.' },
  { id: 2, name: 'Stone Soap Dish', category: 'Home comforts', price: 799, tone: 'clay', description: 'A tactile home for the things you reach for daily.' },
  { id: 3, name: 'Linen Hand Towel', category: 'Bath & body', price: 1099, tone: 'cream', description: 'Soft, absorbent linen with a quietly refined finish.' },
  { id: 4, name: 'Amber Glass Bottle', category: 'Home comforts', price: 899, tone: 'amber', description: 'Simple storage with a warm, purposeful presence.' },
]
const categories = [
  { number: '01 / Bath', title: 'Bath & body', text: 'Soft textures and considered essentials for your daily reset.', href: '/shop.html?category=bath', tone: 'dark' },
  { number: '02 / Home', title: 'Home comforts', text: 'Small details that bring warmth, order, and character home.', href: '/shop.html?category=home', tone: 'gold' },
  { number: '03 / New', title: 'New arrivals', text: 'Fresh finds, just in — selected for the way you live now.', href: '/shop.html?category=new', tone: 'dark' },
]
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 })

function go(path) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
function Link({ href, children, className = '', ...props }) { return <a href={href} className={className} onClick={(e) => { if (href?.startsWith('/')) { e.preventDefault(); go(href) } }} {...props}>{children}</a> }

function Header({ cartCount }) {
  const [open, setOpen] = useState(false)
  useEffect(() => { const close = () => setOpen(false); window.addEventListener('popstate', close); return () => window.removeEventListener('popstate', close) }, [])
  return <header className="header">
    <Link className="brand" href="/">LUVIIO</Link>
    <nav className={`nav-links ${open ? 'is-open' : ''}`} aria-label="Primary navigation"><Link href="/shop.html">Shop</Link><Link href="/#edit">The edit</Link><Link href="/about.html">Our story</Link></nav>
    <div className="header-actions"><Link href="/shop.html" aria-label="Search"><Search size={18} /></Link><Link href="/cart.html" aria-label={`Shopping bag, ${cartCount} items`}><ShoppingBag size={18} /><span className="cart-count">{cartCount}</span></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X size={22} /> : <Menu size={22} />}</button></div>
  </header>
}
function Footer() { return <footer className="footer"><div className="footer-grid"><div><div className="brand">LUVIIO</div><p>Curated essentials for a more considered everyday.</p></div><div><h4>Shop</h4><Link href="/shop.html">All products</Link><Link href="/shop.html?category=new">New arrivals</Link></div><div><h4>About</h4><Link href="/about.html">Our story</Link><Link href="/shipping-policy.html">Shipping</Link></div><div><h4>Help</h4><a href="mailto:support@luviio.in">Contact us</a><Link href="/privacy.html">Privacy</Link></div></div><div className="footer-bottom"><span>© 2026 Luviio</span><span>Made for the everyday.</span></div></footer> }
function Button({ href, children, quiet = false }) { return <Link className={`button ${quiet ? 'button-quiet' : 'button-primary'}`} href={href}>{children}<ArrowRight size={16} /></Link> }

function Home() { return <><main><section className="hero"><div className="hero-copy"><p className="eyebrow reveal">Thoughtful things, beautifully made</p><h1 className="reveal">Make room for<br /><em>the good things.</em></h1><p className="hero-text reveal">Everyday pieces that make your space feel more like yours — from elevated bath essentials to objects worth keeping.</p><div className="hero-actions reveal"><Button href="/shop.html">Explore the collection</Button><Button href="/#edit" quiet>What we sell</Button></div></div><span className="scroll-note">Scroll to discover</span></section><section id="edit" className="edit section"><div className="section-intro"><p className="eyebrow">The Luviio edit</p><h2>Things you use.<br /><em>Things you love.</em></h2><p>A small, considered collection for slow mornings, clean spaces, and everyday rituals.</p></div><div className="category-grid">{categories.map(c => <Link key={c.title} className={`category-card ${c.tone}`} href={c.href}><span>{c.number}</span><div><h3>{c.title}</h3><p>{c.text}</p><strong>Explore <ArrowRight size={15} /></strong></div></Link>)}</div></section><section className="statement"><div><p className="eyebrow">A better everyday</p><h2>Good design,<br />no fuss.</h2></div><p>We look for useful, beautiful products made to last. No clutter. No throwaway trends. Just things that earn their place.</p></section><section className="cta"><p className="eyebrow">Ready when you are</p><h2>Find your next<br /><em>favourite thing.</em></h2><Button href="/shop.html">Shop everything</Button></section></main></> }

function ProductCard({ product, onAdd }) { return <article className="product-card"><Link href={`/product.html?id=${product.id}`} className={`product-image ${product.tone}`}><span>LUVIIO</span></Link><div className="product-meta"><div><p className="product-category">{product.category}</p><h3>{product.name}</h3></div><strong>{money.format(product.price)}</strong></div><button className="add-button" onClick={() => onAdd(product)}>Add to bag <Plus size={15} /></button></article> }
function Shop({ onAdd }) { const [filter, setFilter] = useState('All'); const visible = filter === 'All' ? products : products.filter(p => p.category === filter); return <main className="page-shell"><div className="page-heading"><p className="eyebrow">The collection</p><h1>Everyday,<br /><em>elevated.</em></h1><p>Useful objects and quiet luxuries for the spaces you call home.</p></div><div className="shop-toolbar"><div className="filter-list">{['All', 'Bath & body', 'Home comforts'].map(item => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div><span>{visible.length} pieces <ChevronDown size={15} /></span></div><div className="products-grid">{visible.map(product => <ProductCard key={product.id} product={product} onAdd={onAdd} />)}</div></main> }
function Cart({ cart, setCart }) { const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); const update = (id, amount) => setCart(cart.map(item => item.id === id ? { ...item, quantity: Math.max(1, item.quantity + amount) } : item)); return <main className="page-shell cart-page"><div className="page-heading compact"><p className="eyebrow">Your selection</p><h1>Your bag.</h1></div>{cart.length === 0 ? <div className="empty-state"><p>Your bag is waiting for something good.</p><Button href="/shop.html">Continue shopping</Button></div> : <div className="cart-layout"><div>{cart.map(item => <div className="cart-row" key={item.id}><div className={`product-image small ${item.tone}`}><span>LUVIIO</span></div><div className="cart-info"><p className="product-category">{item.category}</p><h3>{item.name}</h3><div className="quantity"><button onClick={() => update(item.id, -1)} aria-label="Decrease quantity"><Minus size={14} /></button><span>{item.quantity}</span><button onClick={() => update(item.id, 1)} aria-label="Increase quantity"><Plus size={14} /></button></div></div><strong>{money.format(item.price * item.quantity)}</strong></div>)}</div><aside className="summary"><p className="eyebrow">Order summary</p><div><span>Subtotal</span><strong>{money.format(total)}</strong></div><div><span>Shipping</span><span>Calculated at checkout</span></div><button className="button button-primary checkout-button">Checkout <ArrowRight size={16} /></button></aside></div>}</main> }
function InfoPage({ title, eyebrow, children }) { return <main className="page-shell info-page"><div className="page-heading compact"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div><div className="prose">{children}</div></main> }
function App() { const [path, setPath] = useState(window.location.pathname); const [cart, setCart] = useState([]); useEffect(() => { const update = () => setPath(window.location.pathname); window.addEventListener('popstate', update); return () => window.removeEventListener('popstate', update) }, []); useEffect(() => { gsap.fromTo('.reveal, .page-heading, .product-card, .info-page .prose', { y: 24, opacity: 0 }, { y: 0, opacity: 1, duration: .7, stagger: .08, ease: 'power3.out' }); return () => ScrollTrigger.getAll().forEach(t => t.kill()) }, [path]); const add = product => setCart(current => { const found = current.find(item => item.id === product.id); return found ? current.map(item => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }] }); const content = path === '/' ? <Home /> : path === '/shop.html' ? <Shop onAdd={add} /> : path === '/cart.html' ? <Cart cart={cart} setCart={setCart} /> : path === '/about.html' ? <InfoPage eyebrow="Our story" title={<>Good things, <em>well chosen.</em></>}><p>Luviio is a collection of everyday essentials chosen for their usefulness, beauty, and staying power.</p><p>We believe the objects around us shape how a day feels. So we make space for pieces that are tactile, uncomplicated, and made to be lived with.</p></InfoPage> : path === '/shipping-policy.html' ? <InfoPage eyebrow="Delivery" title="Shipping"><p>We carefully pack every order and dispatch across India. Delivery timelines and tracking details are shared by email after your order is confirmed.</p></InfoPage> : path === '/privacy.html' ? <InfoPage eyebrow="The small print" title="Privacy"><p>Your privacy matters to us. We only use information needed to process orders, provide support, and improve your experience.</p></InfoPage> : <InfoPage eyebrow="Luviio" title="Page not found"><p>That page has moved. Let us take you somewhere useful.</p><Button href="/">Return home</Button></InfoPage>; return <><Header cartCount={cart.reduce((sum, i) => sum + i.quantity, 0)} />{content}<Footer /></> }

createRoot(document.getElementById('root')).render(<App />)
