import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, Menu, Search, ShoppingBag, X, LoaderCircle } from 'lucide-react'
import { gsap } from 'gsap'
import './styles.css'
import { API } from './services/backend-api.js'

const getApi = () => API

const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 })

function navigate(href) { window.history.pushState({}, '', href); window.dispatchEvent(new PopStateEvent('popstate')) }
function Link({ href, children, className = '', ...props }) { return <a href={href} className={className} {...props} onClick={(event) => { if (href?.startsWith('/')) { event.preventDefault(); navigate(href) } }}>{children}</a> }
function Button({ href, children, quiet = false, onClick }) { return <Link href={href || '#'} onClick={onClick} className={`button ${quiet ? 'button-quiet' : 'button-primary'}`}>{children}<ArrowRight size={16} /></Link> }
function Status({ loading, error }) { if (loading) return <div className="state-message"><LoaderCircle className="spin" /> Loading your Luviio experience…</div>; if (error) return <div className="state-message error">{error}</div>; return null }

function Header({ cartCount }) {
  const [open, setOpen] = useState(false)
  useEffect(() => { const close = () => setOpen(false); window.addEventListener('popstate', close); return () => window.removeEventListener('popstate', close) }, [])
  return <header className="header"><Link className="brand" href="/">LUVIIO</Link><nav className={`nav-links ${open ? 'is-open' : ''}`} aria-label="Primary navigation"><Link href="/shop">Shop</Link><Link href="/#edit">The edit</Link><Link href="/about">Our story</Link></nav><div className="header-actions"><Link href="/shop" aria-label="Search"><Search size={18} /></Link><Link href="/cart" aria-label={`Shopping bag, ${cartCount} items`}><ShoppingBag size={18} /><span className="cart-count">{cartCount}</span></Link><button className="menu-button" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X size={22} /> : <Menu size={22} />}</button></div></header>
}
function Footer() { return <footer className="footer"><div className="footer-grid"><div><div className="brand">LUVIIO</div><p>Curated essentials for a more considered everyday.</p></div><div><h4>Shop</h4><Link href="/shop">All products</Link><Link href="/shop?category=new">New arrivals</Link></div><div><h4>About</h4><Link href="/about">Our story</Link><Link href="/shipping-policy">Shipping</Link></div><div><h4>Help</h4><a href="mailto:support@luviio.in">Contact us</a><Link href="/privacy">Privacy</Link></div></div><div className="footer-bottom"><span>© 2026 Luviio</span><span>Made for the everyday.</span></div></footer> }

function Home() { return <main><section className="hero"><div className="hero-copy"><p className="eyebrow reveal">Thoughtful things, beautifully made</p><h1 className="reveal">Make room for<br /><em>the good things.</em></h1><p className="hero-text reveal">Everyday pieces that make your space feel more like yours — from elevated bath essentials to objects worth keeping.</p><div className="hero-actions reveal"><Button href="/shop">Explore the collection</Button><Button href="/#edit" quiet>What we sell</Button></div></div><span className="scroll-note">Scroll to discover</span></section><section id="edit" className="edit section"><div className="section-intro"><p className="eyebrow">The Luviio edit</p><h2>Things you use.<br /><em>Things you love.</em></h2><p>A small, considered collection for slow mornings, clean spaces, and everyday rituals.</p></div><div className="category-grid"><Link className="category-card dark" href="/shop?category=bath"><span>01 / Bath</span><div><h3>Bath &amp; body</h3><p>Soft textures and considered essentials for your daily reset.</p><strong>Explore <ArrowRight size={15} /></strong></div></Link><Link className="category-card gold" href="/shop?category=home"><span>02 / Home</span><div><h3>Home comforts</h3><p>Small details that bring warmth, order, and character home.</p><strong>Explore <ArrowRight size={15} /></strong></div></Link><Link className="category-card dark" href="/shop?category=new"><span>03 / New</span><div><h3>New arrivals</h3><p>Fresh finds, just in — selected for the way you live now.</p><strong>Explore <ArrowRight size={15} /></strong></div></Link></div></section><section className="statement"><div><p className="eyebrow">A better everyday</p><h2>Good design,<br />no fuss.</h2></div><p>We look for useful, beautiful products made to last. No clutter. No throwaway trends. Just things that earn their place.</p></section><section className="cta"><p className="eyebrow">Ready when you are</p><h2>Find your next<br /><em>favourite thing.</em></h2><Button href="/shop">Shop everything</Button></section></main> }

function ProductCard({ product, onAdd }) { return <article className="product-card"><Link href={`/product?slug=${encodeURIComponent(product.slug || product.id)}`} className="product-image"><span>{product.name?.slice(0, 1) || 'L'}</span></Link><div className="product-meta"><div><p className="product-category">{product.category?.name || product.category || 'Luviio collection'}</p><h3>{product.name}</h3></div><strong>{money.format(product.price || 0)}</strong></div><button className="add-button" onClick={() => onAdd(product)}>Add to bag <ArrowRight size={15} /></button></article> }
function useRequest(request, deps = []) { const [state, setState] = useState({ loading: true, error: '', data: null }); useEffect(() => { let active = true; setState({ loading: true, error: '', data: null }); request().then((data) => active && setState({ loading: false, error: '', data })).catch((error) => active && setState({ loading: false, error: error.message || 'Something went wrong. Please try again.', data: null })); return () => { active = false } }, deps); return state }
function Shop({ onAdd }) { const { loading, error, data } = useRequest(() => getApi()?.getProducts({ page: 1, page_size: 24 }), []); const products = Array.isArray(data) ? data : data?.items || data?.products || []; return <main className="page-shell"><div className="page-heading"><p className="eyebrow">The collection</p><h1>Everyday,<br /><em>elevated.</em></h1><p>Useful objects and quiet luxuries for the spaces you call home.</p></div><Status loading={loading} error={error} /><div className="products-grid">{products.map((product) => <ProductCard key={product.id || product.slug} product={product} onAdd={onAdd} />)}</div>{!loading && !error && products.length === 0 && <div className="empty-state">No products are available right now.</div>}</main> }
function Cart() { const { loading, error, data } = useRequest(() => getApi()?.getCart(), []); const items = data?.items || data || []; return <main className="page-shell cart-page"><div className="page-heading compact"><p className="eyebrow">Your selection</p><h1>Your bag.</h1></div><Status loading={loading} error={error} />{!loading && !error && (!Array.isArray(items) || items.length === 0) ? <div className="empty-state"><p>Your bag is waiting for something good.</p><Button href="/shop">Continue shopping</Button></div> : <div className="cart-layout"><div>{Array.isArray(items) && items.map((item) => <div className="cart-row" key={item.id || item.product_id}><div className="product-image small"><span>L</span></div><div className="cart-info"><p className="product-category">Product</p><h3>{item.product?.name || item.name || 'Selected item'}</h3><p>Quantity: {item.quantity}</p></div><strong>{money.format(item.total || item.price || 0)}</strong></div>)}</div><aside className="summary"><p className="eyebrow">Order summary</p><div><span>Subtotal</span><strong>{money.format(data?.subtotal || 0)}</strong></div><Button href="/checkout">Checkout</Button></aside></div>}</main> }
function DataPage({ title, eyebrow, request, render }) { const { loading, error, data } = useRequest(request, []); return <main className="page-shell info-page"><div className="page-heading compact"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div><Status loading={loading} error={error} />{!loading && !error && render(data)}</main> }
function App() { const [path, setPath] = useState(window.location.pathname); const [cartCount, setCartCount] = useState(0); useEffect(() => { const update = () => setPath(window.location.pathname); window.addEventListener('popstate', update); return () => window.removeEventListener('popstate', update) }, []); useEffect(() => { gsap.fromTo('.reveal, .page-heading, .product-card, .info-page .prose', { y: 20, opacity: 0 }, { y: 0, opacity: 1, duration: .65, stagger: .06, ease: 'power3.out' }) }, [path]); const add = async (product) => { try { await getApi()?.addCartItem(product.id, 1); setCartCount((count) => count + 1) } catch (error) { window.alert(error.message || 'Unable to add this item right now.') } }; let content = path === '/' ? <Home /> : path === '/shop' ? <Shop onAdd={add} /> : path === '/cart' ? <Cart /> : path === '/profile' ? <DataPage eyebrow="Your account" title="Profile" request={() => getApi()?.getMe()} render={(data) => <div className="prose"><p>{data?.full_name || data?.email || 'Your Luviio profile'}</p><Button href="/orders">View order history</Button></div>} /> : path === '/orders' ? <DataPage eyebrow="Your account" title="Order history" request={() => getApi()?.getMyOrders()} render={(data) => <div className="prose">{(data?.items || data || []).map((order) => <p key={order.id}>Order {order.id} — {order.status}</p>)}</div>} /> : path === '/about' ? <DataPage eyebrow="Our story" title={<>Good things, <em>well chosen.</em></>} request={() => Promise.resolve({})} render={() => <div className="prose"><p>Luviio is a collection of everyday essentials chosen for their usefulness, beauty, and staying power.</p></div>} /> : path === '/checkout' ? <DataPage eyebrow="Secure checkout" title="Complete your order" request={() => getApi()?.getCart()} render={() => <div className="prose"><p>Your live cart is ready. Continue to payment to complete your order.</p><Button href="/paywall">Continue to payment</Button></div>} /> : path === '/paywall' ? <DataPage eyebrow="Payment" title="Secure payment" request={() => getApi()?.getPricingConfig()} render={() => <div className="prose"><p>Payment is securely handled through Luviio checkout.</p></div>} /> : <DataPage eyebrow="Luviio" title="Page not found" request={() => Promise.resolve({})} render={() => <div className="prose"><p>That page has moved.</p><Button href="/">Return home</Button></div>} />; return <><Header cartCount={cartCount} />{content}<Footer /></> }

createRoot(document.getElementById('root')).render(<App />)
