import { useEffect, useMemo, useState } from 'react';
import { RiRefreshLine, RiSaveLine, RiDeleteBinLine, RiSendPlaneLine, RiShieldCheckLine } from '@remixicon/react';
import { adminService, itemsOfList } from '../../services/admin';
import { useToast } from '../../context/ToastContext';

const pretty = (value) => {
  if (value === null || value === undefined) return '—';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
};

function Toolbar({ title, description, onRefresh, children }) {
  return <div className="admin-toolbar"><div><h2>{title}</h2><p>{description}</p></div><div className="btn-row">{children}<button type="button" className="btn btn-quiet btn-sm" onClick={onRefresh}><RiRefreshLine size={16} /> Refresh</button></div></div>;
}

export default function OperationsPanel({ section }) {
  if (section === 'inventory') return <InventoryPanel />;
  if (section === 'shipping') return <ShippingPanel />;
  if (section === 'subscriptions') return <SubscriptionPanel />;
  if (section === 'user-actions') return <UserActionsPanel />;
  if (section === 'rbac') return <RbacPanel />;
  if (section === 'notifications') return <NotificationsPanel />;
  if (section === 'settings') return <SettingsPanel />;
  return <UnavailablePanel section={section} />;
}

function InventoryPanel() {
  const { toast } = useToast();
  const [lowStock, setLowStock] = useState([]);
  const [loading, setLoading] = useState(true);
  const [scanning, setScanning] = useState(false);
  const load = async () => { setLoading(true); try { setLowStock(itemsOfList(await adminService.lowStock())); } catch (e) { toast.error(e.message || 'Unable to load inventory.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const scan = async () => { setScanning(true); try { const r = await adminService.scanLowStock(); toast.success(`${r?.alerts_published ?? 0} low-stock alert(s) published.`); await load(); } catch (e) { toast.error(e.message || 'Low-stock scan failed.'); } finally { setScanning(false); } };
  const release = async () => { try { const r = await adminService.releaseStaleOrders(30); toast.success(`${r?.orders_released ?? 0} stale order(s) released.`); } catch (e) { toast.error(e.message || 'Unable to release stale orders.'); } };
  return <section className="admin-panel"><div className="admin-card"><Toolbar title="Inventory" description="Monitor low stock and release abandoned checkout reservations." onRefresh={load}><button type="button" className="btn btn-sm" disabled={scanning} onClick={scan}>{scanning ? 'Scanning…' : 'Scan low stock'}</button><button type="button" className="btn btn-quiet btn-sm" onClick={release}>Release stale stock</button></Toolbar><div className="admin-stats"><div className="admin-stat"><div className="stat-label">Low-stock products</div><div className="stat-value">{loading ? '…' : lowStock.length}</div><div className="stat-hint">At or below configured threshold</div></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Stock</th><th>Threshold</th></tr></thead><tbody>{lowStock.length ? lowStock.map((p, i) => <tr key={p.id || i}><td className="td-strong">{pretty(p.name || p.title || p.product_name)}</td><td className="td-gold">{pretty(p.stock ?? p.quantity ?? p.stock_level)}</td><td>{pretty(p.low_stock_threshold ?? p.threshold)}</td></tr>) : <tr><td colSpan="3"><div className="admin-empty">{loading ? 'Loading inventory…' : 'No low-stock products.'}</div></td></tr>}</tbody></table></div></div></section>;
}

function ShippingPanel() {
  const { toast } = useToast();
  const empty = { name: '', type: 'flat', base_rate: 0, threshold: '', per_item_rate: '', weight_rate: '', estimated_days: 3, is_active: true, sort_order: 0 };
  const [methods, setMethods] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setMethods(itemsOfList(await adminService.shippingMethods(false))); } catch (e) { toast.error(e.message || 'Unable to load shipping methods.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async (e) => { e.preventDefault(); try { const payload = {...form, base_rate: Number(form.base_rate || 0), estimated_days: Number(form.estimated_days || 3), sort_order: Number(form.sort_order || 0), threshold: form.threshold === '' ? null : Number(form.threshold), per_item_rate: form.per_item_rate === '' ? null : Number(form.per_item_rate), weight_rate: form.weight_rate === '' ? null : Number(form.weight_rate) }; if (editing) await adminService.updateShipping(editing, payload); else await adminService.createShipping(payload); toast.success(editing ? 'Shipping method updated.' : 'Shipping method created.'); setForm(empty); setEditing(null); await load(); } catch (e) { toast.error(e.message || 'Unable to save shipping method.'); } };
  const edit = (m) => { setEditing(m.id); setForm({...empty, ...m}); };
  const remove = async (id) => { if (!window.confirm('Delete this shipping method?')) return; try { await adminService.deleteShipping(id); toast.success('Shipping method deleted.'); await load(); } catch (e) { toast.error(e.message || 'Unable to delete shipping method.'); } };
  return <section className="admin-panel"><div className="admin-card"><Toolbar title="Shipping" description="Manage the shipping methods exposed to checkout." onRefresh={load} /><form onSubmit={save}><div className="field-grid"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="flat">Flat</option><option value="free_threshold">Free above threshold</option><option value="per_item">Per item</option><option value="weight">By weight</option></select></label><label>Base rate<input type="number" min="0" step="0.01" value={form.base_rate} onChange={e=>setForm({...form,base_rate:e.target.value})}/></label><label>Threshold<input type="number" min="0" step="0.01" value={form.threshold} onChange={e=>setForm({...form,threshold:e.target.value})}/></label><label>Per-item rate<input type="number" min="0" step="0.01" value={form.per_item_rate} onChange={e=>setForm({...form,per_item_rate:e.target.value})}/></label><label>Weight rate<input type="number" min="0" step="0.01" value={form.weight_rate} onChange={e=>setForm({...form,weight_rate:e.target.value})}/></label><label>Estimated days<input type="number" min="1" max="30" value={form.estimated_days} onChange={e=>setForm({...form,estimated_days:e.target.value})}/></label><label>Sort order<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label className="checkbox-field"><input type="checkbox" checked={!!form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active</label></div><div className="btn-row" style={{marginTop:14}}><button className="btn btn-sm" type="submit"><RiSaveLine size={16}/>{editing ? 'Update method' : 'Create method'}</button>{editing && <button type="button" className="btn btn-quiet btn-sm" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Type</th><th>Base</th><th>Days</th><th>Status</th><th></th></tr></thead><tbody>{methods.length ? methods.map(m=><tr key={m.id}><td className="td-strong">{m.name}</td><td>{m.type}</td><td className="td-gold">₹{pretty(m.base_rate)}</td><td>{pretty(m.estimated_days)}</td><td><span className={`admin-pill ${m.is_active?'pill-success':'pill-muted'}`}>{m.is_active?'Active':'Inactive'}</span></td><td><div className="btn-row"><button className="icon-btn" onClick={()=>edit(m)} title="Edit"><RiSaveLine size={15}/></button><button className="icon-btn" onClick={()=>remove(m.id)} title="Delete"><RiDeleteBinLine size={15}/></button></div></td></tr>) : <tr><td colSpan="6"><div className="admin-empty">{loading?'Loading shipping methods…':'No shipping methods configured.'}</div></td></tr>}</tbody></table></div></section>;
}

function SubscriptionPanel() {
  const { toast } = useToast(); const [plans,setPlans]=useState([]); const [loading,setLoading]=useState(true); const [editing,setEditing]=useState(null); const empty={tier:'premium',name:'',price_inr:'',duration_days:30,description:'',is_active:true}; const [form,setForm]=useState(empty);
  const load=async()=>{setLoading(true);try{setPlans(itemsOfList(await adminService.subscriptionPlans(true)));}catch(e){toast.error(e.message||'Unable to load subscription plans.')}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
  const save=async(e)=>{e.preventDefault();try{const payload={...form,price_inr:Number(form.price_inr),duration_days:Number(form.duration_days)};if(editing) await adminService.updateSubscription(editing,payload); else await adminService.createSubscription(payload);toast.success(editing?'Plan updated.':'Plan created.');setEditing(null);setForm(empty);await load()}catch(e){toast.error(e.message||'Unable to save plan.')}};
  return <section className="admin-panel"><div className="admin-card"><Toolbar title="Subscription plans" description="Manage the plans and membership pricing available to customers." onRefresh={load}/><form onSubmit={save}><div className="field-grid"><label>Tier<select value={form.tier} onChange={e=>setForm({...form,tier:e.target.value})}><option value="premium">Premium</option><option value="platinum">Platinum</option><option value="free">Free</option></select></label><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Price (INR)<input required type="number" min="0.01" step="0.01" value={form.price_inr} onChange={e=>setForm({...form,price_inr:e.target.value})}/></label><label>Duration (days)<input required type="number" min="1" value={form.duration_days} onChange={e=>setForm({...form,duration_days:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}>Description<textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="checkbox-field"><input type="checkbox" checked={!!form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active</label></div><div className="btn-row" style={{marginTop:14}}><button className="btn btn-sm"><RiSaveLine size={16}/>{editing?'Update plan':'Create plan'}</button>{editing&&<button type="button" className="btn btn-quiet btn-sm" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Tier</th><th>Name</th><th>Price</th><th>Duration</th><th>Status</th><th></th></tr></thead><tbody>{plans.length?plans.map(p=><tr key={p.id}><td><span className="admin-pill pill-gold">{p.tier}</span></td><td className="td-strong">{p.name}</td><td className="td-gold">₹{pretty(p.price_inr)}</td><td>{pretty(p.duration_days)} days</td><td><span className={`admin-pill ${p.is_active?'pill-success':'pill-muted'}`}>{p.is_active?'Active':'Inactive'}</span></td><td><button className="icon-btn" onClick={()=>{setEditing(p.id);setForm({...empty,...p})}}><RiSaveLine size={15}/></button></td></tr>):<tr><td colSpan="6"><div className="admin-empty">{loading?'Loading plans…':'No subscription plans.'}</div></td></tr>}</tbody></table></div></section>;
}

function UserActionsPanel() {
  const { toast }=useToast(); const [userId,setUserId]=useState(''); const [data,setData]=useState(null); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState('');
  const load=async()=>{if(!userId.trim())return;setLoading(true);try{setData(await adminService.userActions(userId.trim()))}catch(e){toast.error(e.message||'Unable to load user actions.')}finally{setLoading(false)}};
  const toggle=async(action,enabled)=>{setBusy(action);try{if(enabled) await adminService.setUserAction(userId.trim(),action,false,'Disabled by admin'); else await adminService.removeUserAction(userId.trim(),action);await load()}catch(e){toast.error(e.message||'Unable to update user action.')}finally{setBusy('')}};
  return <section className="admin-panel"><div className="admin-card"><Toolbar title="User actions" description="Disable or restore individual capabilities for a specific customer." onRefresh={load}><RiShieldCheckLine size={18}/></Toolbar><div className="admin-toolbar" style={{border:0,paddingBottom:0,marginBottom:0}}><input className="admin-inline admin-inline-sm" style={{width:'min(420px,100%)',border:'1px solid var(--line)',padding:'10px 12px'}} placeholder="Enter user UUID" value={userId} onChange={e=>setUserId(e.target.value)}/><button className="btn btn-sm" onClick={load}>Load controls</button></div>{loading?<div className="admin-empty">Loading controls…</div>:data&&<div className="admin-stats">{(data.all_actions||[]).map(action=>{const row=(data.controls||[]).find(c=>c.action===action);const blocked=row?.enabled===false;return <div className="admin-stat" key={action}><div className="stat-label">{action.replaceAll('_',' ')}</div><div className="stat-value" style={{fontSize:22}}>{blocked?'Blocked':'Enabled'}</div><div className="btn-row" style={{marginTop:12}}><button className="btn btn-quiet btn-sm" disabled={busy===action} onClick={()=>toggle(action,blocked)}>{busy===action?'Saving…':blocked?'Restore':'Disable'}</button></div></div>})}</div>}</div></section>;
}

function RbacPanel(){const {toast}=useToast();const [catalogue,setCatalogue]=useState([]);const [matrix,setMatrix]=useState(null);const [loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{const [c,p]=await Promise.all([adminService.permissionCatalogue(),adminService.permissions()]);setCatalogue(c||[]);setMatrix(p||{})}catch(e){toast.error(e.message||'Unable to load permissions.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);const rows=useMemo(()=>{if(!matrix?.effective)return[];return Object.entries(matrix.effective).flatMap(([role,perms])=>Object.entries(perms||{}).map(([permission,enabled])=>({role,permission,enabled})))},[matrix]);const toggle=async(row)=>{try{await adminService.togglePermission(row.role,row.permission,!row.enabled);toast.success('Permission updated.');await load()}catch(e){toast.error(e.message||'Unable to update permission.')}};return <section className="admin-panel"><div className="admin-card"><Toolbar title="Roles & permissions" description="Review the effective RBAC matrix and role-level overrides." onRefresh={load}/><div className="admin-page-note">{loading?'Loading…':`${rows.length} permission entries loaded.`}</div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Role</th><th>Permission</th><th>State</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={`${r.role}:${r.permission}`}><td className="td-strong">{r.role}</td><td>{r.permission}</td><td><span className={`admin-pill ${r.enabled?'pill-success':'pill-danger'}`}>{r.enabled?'Allowed':'Denied'}</span></td><td><button className="btn btn-quiet btn-sm" onClick={()=>toggle(r)}>{r.enabled?'Deny':'Allow'}</button></td></tr>)}</tbody></table></div></section>}

function NotificationsPanel(){const {toast}=useToast();const [stats,setStats]=useState(null);const [userIds,setUserIds]=useState('');const [title,setTitle]=useState('');const [body,setBody]=useState('');const [sending,setSending]=useState(false);const load=async()=>{try{setStats(await adminService.pushStats())}catch(e){toast.error(e.message||'Unable to load notification stats.')}};useEffect(()=>{load()},[]);const send=async(e)=>{e.preventDefault();setSending(true);try{const r=await adminService.sendPush({user_ids:userIds.split(',').map(v=>v.trim()).filter(Boolean),title,body});toast.success(`${r?.sent ?? r?.success ?? 0} notification(s) dispatched.`);setTitle('');setBody('')}catch(e){toast.error(e.message||'Unable to send notifications.')}finally{setSending(false)}};return <section className="admin-panel"><div className="admin-card"><Toolbar title="Notifications" description="Monitor Web Push and send an authenticated batch notification." onRefresh={load}/><div className="admin-stats"><div className="admin-stat"><div className="stat-label">Subscribers</div><div className="stat-value">{pretty(stats?.subscribers ?? stats?.total_subscriptions)}</div></div><div className="admin-stat"><div className="stat-label">Active endpoints</div><div className="stat-value">{pretty(stats?.active ?? stats?.active_subscriptions)}</div></div></div><form onSubmit={send}><div className="field-grid"><label style={{gridColumn:'1/-1'}}>User IDs (comma separated)<input value={userIds} onChange={e=>setUserIds(e.target.value)} placeholder="UUID, UUID"/></label><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Message<textarea required value={body} onChange={e=>setBody(e.target.value)}/></label></div><button className="btn btn-sm" disabled={sending} style={{marginTop:14}}><RiSendPlaneLine size={16}/>{sending?'Sending…':'Send notification'}</button></form></div></section>}

function SettingsPanel(){const {toast}=useToast();const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{setItems(itemsOfList(await adminService.settings()))}catch(e){toast.error(e.message||'Unable to load settings.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);const save=async(s)=>{try{let value=s.value; if(s.data_type==='boolean') value=String(value)==='true'; else if(['integer','number','float'].includes(s.data_type)) value=Number(value); else if(s.data_type==='json') value=JSON.parse(value);await adminService.updateSetting(s.key,value,'Admin UI update');toast.success(`${s.key} updated.`);await load()}catch(e){toast.error(e.message||'Unable to update setting.')}};return <section className="admin-panel"><div className="admin-card"><Toolbar title="System settings" description="View and mutate dynamic operational settings through the backend settings domain." onRefresh={load}/></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Key</th><th>Category</th><th>Value</th><th>Access</th><th></th></tr></thead><tbody>{items.map(s=><SettingRow key={s.key} setting={s} onSave={save}/>)}{!items.length&&<tr><td colSpan="5"><div className="admin-empty">{loading?'Loading settings…':'No settings returned.'}</div></td></tr>}</tbody></table></div></section>}
function SettingRow({setting,onSave}){const [value,setValue]=useState(typeof setting.value==='object'?JSON.stringify(setting.value):String(setting.value??''));const locked=setting.is_system_locked;return <tr><td className="td-strong">{setting.key}<div className="table-sub">{setting.description||''}</div></td><td>{setting.category}</td><td><input className="admin-inline admin-inline-sm" disabled={locked} value={value} onChange={e=>setValue(e.target.value)}/></td><td><span className={`admin-pill ${locked?'pill-muted':'pill-info'}`}>{locked?'Locked':setting.is_public?'Public':'Private'}</span></td><td><button className="icon-btn" disabled={locked} onClick={()=>onSave({...setting,value})} title="Save"><RiSaveLine size={15}/></button></td></tr>}

function UnavailablePanel({section}){return <section className="admin-panel"><div className="admin-card"><div className="admin-toolbar"><div><h2>{section.replaceAll('-',' ')}</h2><p>This management surface is reserved for a backend endpoint that is not currently exposed.</p></div></div><div className="admin-page-note">No fake data or destructive client-side fallback is used here.</div></div></section>}
