import { useCallback, useEffect, useMemo, useState } from 'react';
import { RiAddLine, RiDeleteBinLine, RiEditLine, RiImageAddLine, RiSearchLine, RiCloseLine, RiStarFill } from '@remixicon/react';
import { adminService, itemsOfList } from '../../services/admin';
import { useToast } from '../../context/ToastContext';
import { formatMoney } from '../../utils/format';
import { ErrorState, Spinner } from '../../components/ui/States';
import AdminModal from './Modal';
import '../../styles/product-admin.css';

const PAGE_SIZE = 100;
const MAX_IMAGES = 10;
const blank = { name:'', slug:'', sku:'', category_id:'', price:'', compare_price:'', stock:'0', low_stock_threshold:'10', short_description:'', description:'', image_url:'', is_active:true, images:[] };
const toForm = (p) => { const images = Array.isArray(p.images) ? p.images.filter(Boolean) : (p.image_url ? [p.image_url] : []); return { ...blank, name:p.name||'', slug:p.slug||'', sku:p.sku||'', category_id:p.category_id||'', price:p.price!=null?String(p.price):'', compare_price:p.compare_price!=null?String(p.compare_price):'', stock:p.stock!=null?String(p.stock):'0', low_stock_threshold:p.low_stock_threshold!=null?String(p.low_stock_threshold):'10', short_description:p.short_description||'', description:p.description||'', image_url:images[0]||'', is_active:p.is_active!==false, images }; };

export default function ProductsPanel({ capabilities={} }) {
  const canCreate = capabilities.productCreate === true;
  const canUpdate = capabilities.productUpdate === true;
  const canDelete = capabilities.productDelete === true;
  const canManageImages = canUpdate;
  const { toast } = useToast();
  const [items,setItems]=useState(null); const [categories,setCategories]=useState([]); const [error,setError]=useState('');
  const [search,setSearch]=useState(''); const [catFilter,setCatFilter]=useState('');
  const [editing,setEditing]=useState(false); const [editingId,setEditingId]=useState(null); const [form,setForm]=useState(blank);
  const [saving,setSaving]=useState(false); const [busyId,setBusyId]=useState(null); const [selectedFiles,setSelectedFiles]=useState([]);
  const [deletingImage,setDeletingImage]=useState(null); const [primaryBusy,setPrimaryBusy]=useState(null);

  const load=useCallback(async()=>{setError('');try{const[p,c]=await Promise.all([adminService.listProducts({page:1,page_size:PAGE_SIZE}),adminService.categories()]);setItems(itemsOfList(p));setCategories(itemsOfList(c));}catch(e){setError(e.message||'Unable to load products.');}},[]);
  useEffect(()=>{load();},[load]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return(items||[]).filter(p=>(!catFilter||String(p.category_id||p.category)===String(catFilter))&&(!q||[p.name,p.slug,p.sku].some(v=>String(v||'').toLowerCase().includes(q))));},[items,search,catFilter]);

  const openCreate=()=>{if(!canCreate)return;setEditingId(null);setForm({...blank});setSelectedFiles([]);setEditing(true);};
  const openEdit=(p)=>{if(!canUpdate)return;setEditingId(p.id);setForm(toForm(p));setSelectedFiles([]);setEditing(true);};
  const closeEditor=()=>{if(saving)return;setEditing(false);setSelectedFiles([]);};
  const selectFiles=(e)=>{if(!canManageImages)return;const incoming=Array.from(e.target.files||[]);if(!incoming.length)return;if(incoming.some(f=>!f.type.startsWith('image/')))return toast.error('Please choose image files only.');if(incoming.some(f=>f.size>2*1024*1024))return toast.error('Each image must be 2 MB or smaller.');if(form.images.length+selectedFiles.length+incoming.length>MAX_IMAGES)return toast.error(`Maximum ${MAX_IMAGES} images per product.`);setSelectedFiles(v=>[...v,...incoming]);e.target.value='';};
  const removeImage=async(index)=>{if(!editingId||!canManageImages)return;setDeletingImage(index);try{const r=await adminService.deleteProductImage(editingId,index);const images=Array.isArray(r?.images)?r.images:form.images.filter((_,i)=>i!==index);setForm(v=>({...v,images,image_url:images[0]||''}));toast.success('Image removed.');}catch(e){toast.error(e.message||'Unable to remove image.');}finally{setDeletingImage(null);}};
  const setPrimary=async(index)=>{if(!editingId||index===0||!canManageImages)return;setPrimaryBusy(index);try{const ordered=[form.images[index],...form.images.filter((_,i)=>i!==index)];const r=await adminService.reorderProductImages(editingId,ordered);const images=Array.isArray(r?.images)?r.images:ordered;setForm(v=>({...v,images,image_url:images[0]||''}));toast.success('Primary image updated.');}catch(e){toast.error(e.message||'Unable to set primary image.');}finally{setPrimaryBusy(null);}};
  const validate=()=>{if(form.name.trim().length<2)return'Name must be at least 2 characters.';if(!/^[a-z0-9-]+$/.test(form.slug.trim().toLowerCase()))return'Slug can only contain lowercase letters, numbers and dashes.';if(!(Number(form.price)>0))return'Price must be greater than zero.';if(form.compare_price!==''&&Number(form.compare_price)<=Number(form.price))return'Compare-at price must be greater than the price.';if(Number(form.stock)<0)return'Stock cannot be negative.';return null;};
  const save=async(e)=>{e.preventDefault();if(editingId&&!canUpdate)return;if(!editingId&&!canCreate)return;const problem=validate();if(problem)return toast.error(problem);setSaving(true);try{const images=form.images.filter(Boolean);const base={category_id:form.category_id||undefined,image_url:images[0]||form.image_url.trim()||undefined,images,short_description:form.short_description.trim()||undefined,description:form.description.trim()||undefined,is_active:form.is_active,price:Number(form.price),compare_price:form.compare_price===''?undefined:Number(form.compare_price),stock:Number(form.stock)||0,low_stock_threshold:Number(form.low_stock_threshold)||0};if(editingId){await adminService.updateProduct(editingId,base);if(selectedFiles.length)await adminService.uploadProductImages(editingId,selectedFiles);toast.success('Product updated.');}else{const data={...base,name:form.name.trim(),slug:form.slug.trim().toLowerCase(),sku:form.sku.trim()||undefined};if(selectedFiles.length)await adminService.createProductWithImages(data,selectedFiles);else await adminService.createProduct(data);toast.success('Product created.');}setEditing(false);setSelectedFiles([]);await load();}catch(e){toast.error(e.message||'Unable to save product.');}finally{setSaving(false);}};
  const remove=async(p)=>{if(!canDelete)return;if(!window.confirm(`Delete "${p.name}"? This cannot be undone.`))return;setBusyId(p.id);try{await adminService.deleteProduct(p.id);toast.success('Product deleted.');await load();}catch(e){toast.error(e.message||'Unable to delete product.');}finally{setBusyId(null);}};

  if(error)return <ErrorState message={error} onRetry={load}/>; if(items===null)return <Spinner label="Loading products…"/>;
  return <div className="products-admin">
    <div className="admin-head"><div><h1>Products</h1><p className="admin-sub">{filtered.length} of {items.length} shown · manage catalogue</p></div>{canCreate&&<button className="btn btn-sm" onClick={openCreate}><RiAddLine size={16}/> Add product</button>}</div>
    <div className="admin-table-wrap"><div className="admin-toolbar"><label className="admin-search"><RiSearchLine size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, SKU or slug…"/></label><select className="admin-select" value={catFilter} onChange={e=>setCatFilter(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.id||c.slug} value={c.id||c.slug}>{c.name}</option>)}</select></div>
      {filtered.length===0?<div className="admin-empty">No products match.</div>:<table className="admin-table"><thead><tr><th>Product</th><th>SKU</th><th>Price</th><th>Stock</th><th>Category</th><th>Status</th>{(canUpdate||canDelete)&&<th>Actions</th>}</tr></thead><tbody>{filtered.map(p=>{const cat=categories.find(c=>c.id===p.category_id);return <tr key={p.id}><td><div className="product-cell">{p.image_url?<img src={p.image_url} alt="" loading="lazy"/>:<div className="product-thumb"><RiImageAddLine size={17}/></div>}<div><div className="td-strong">{p.name}</div><div className="td-dim">{p.slug}</div></div></div></td><td className="td-dim">{p.sku||'—'}</td><td className="td-gold">{formatMoney(Number(p.price)||0)}</td><td>{p.stock}</td><td className="td-dim">{cat?.name||'—'}</td><td>{p.is_active===false?<span className="admin-pill pill-danger">Inactive</span>:<span className="admin-pill pill-success">Active</span>}</td>{(canUpdate||canDelete)&&<td><div className="btn-row">{canUpdate&&<button className="icon-btn" onClick={()=>openEdit(p)} title="Edit product" aria-label={`Edit ${p.name}`}><RiEditLine size={16}/></button>}{canDelete&&<button className="icon-btn danger-action" onClick={()=>remove(p)} disabled={busyId===p.id} title="Delete product" aria-label={`Delete ${p.name}`}><RiDeleteBinLine size={16}/></button>}</div></td>}</tr>;})}</tbody></table>}
    </div>

    {editing&&<AdminModal className="product-editor-modal" title={editingId?'Edit product':'Add product'} sub={editingId?'Update catalogue information, pricing and media.':'Create a complete catalogue listing.'} onClose={closeEditor}>
      <form className="product-editor" onSubmit={save}>
        <div className="editor-section"><div className="editor-section-head"><div><h3>Basic information</h3><p>Customer-facing product identity.</p></div></div><div className="field-grid"><div className="field"><label htmlFor="product-name">Name *</label><input id="product-name" autoFocus required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></div><div className="field"><label htmlFor="product-sku">SKU</label><input id="product-sku" value={form.sku} onChange={e=>setForm(v=>({...v,sku:e.target.value}))}/></div></div><div className="field-grid"><div className="field"><label htmlFor="product-slug">Slug *</label><input id="product-slug" required disabled={!!editingId} value={form.slug} onChange={e=>setForm(v=>({...v,slug:e.target.value.toLowerCase()}))}/></div><div className="field"><label htmlFor="product-category">Category</label><select id="product-category" value={form.category_id} onChange={e=>setForm(v=>({...v,category_id:e.target.value}))}><option value="">None</option>{categories.map(c=><option key={c.id||c.slug} value={c.id||c.slug}>{c.name}</option>)}</select></div></div></div>
        <div className="editor-section"><div className="editor-section-head"><div><h3>Pricing & inventory</h3><p>Commercial values used by the catalogue.</p></div></div><div className="field-grid"><div className="field"><label htmlFor="product-price">Price (₹) *</label><input id="product-price" required type="number" min="0.01" step="0.01" value={form.price} onChange={e=>setForm(v=>({...v,price:e.target.value}))}/></div><div className="field"><label htmlFor="product-compare">Compare-at price</label><input id="product-compare" type="number" min="0" step="0.01" value={form.compare_price} onChange={e=>setForm(v=>({...v,compare_price:e.target.value}))}/></div></div><div className="field-grid"><div className="field"><label htmlFor="product-stock">Stock</label><input id="product-stock" type="number" min="0" step="1" value={form.stock} onChange={e=>setForm(v=>({...v,stock:e.target.value}))}/></div><div className="field"><label htmlFor="product-threshold">Low-stock threshold</label><input id="product-threshold" type="number" min="0" step="1" value={form.low_stock_threshold} onChange={e=>setForm(v=>({...v,low_stock_threshold:e.target.value}))}/></div></div></div>
        <div className="editor-section"><div className="editor-section-head"><div><h3>Product media</h3><p>First image is the primary catalogue image.</p></div><span className="image-count">{form.images.length+selectedFiles.length}/{MAX_IMAGES}</span></div><label className="upload-drop"><RiImageAddLine size={20}/><span><strong>Add product images</strong><small>PNG, JPG or WebP · max 2 MB each</small></span><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={selectFiles} disabled={!canManageImages||form.images.length+selectedFiles.length>=MAX_IMAGES}/></label>{form.images.length>0&&<div className="admin-image-grid">{form.images.map((src,index)=><div className={`admin-image-item ${index===0?'is-primary':''}`} key={`${src}-${index}`}><img src={src} alt={`Product image ${index+1}`}/><span className="admin-image-index">{index===0?<><RiStarFill size={12}/> Primary</>:index+1}</span><div className="admin-image-actions">{index!==0&&editingId&&canManageImages&&<button type="button" className="btn btn-quiet btn-sm" disabled={primaryBusy===index} onClick={()=>setPrimary(index)}>{primaryBusy===index?'Saving…':'Set primary'}</button>}{editingId&&canManageImages&&<button type="button" className="icon-btn" disabled={deletingImage===index} onClick={()=>removeImage(index)} aria-label="Remove image"><RiCloseLine size={14}/></button>}</div></div>)}</div>}{selectedFiles.length>0&&<div className="selected-image-list">{selectedFiles.map((f,i)=><div className="selected-image-row" key={`${f.name}-${i}`}><span>{f.name}</span></div>)}</div>}</div>
        <div className="editor-section"><div className="editor-section-head"><div><h3>Descriptions</h3><p>Keep the listing useful and concise.</p></div></div><div className="field"><label htmlFor="product-short">Short description</label><input id="product-short" value={form.short_description} onChange={e=>setForm(v=>({...v,short_description:e.target.value}))}/></div><div className="field"><label htmlFor="product-description">Description</label><textarea id="product-description" rows="5" value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></div></div>
        <div className="editor-footer"><label className="check-line"><input type="checkbox" checked={form.is_active} onChange={e=>setForm(v=>({...v,is_active:e.target.checked}))}/> <span><strong>Active listing</strong><small>Visible to customers when published.</small></span></label><div className="btn-row"><button type="button" className="btn btn-quiet" onClick={closeEditor} disabled={saving}>Cancel</button><button className="btn" disabled={saving}>{saving?'Saving…':editingId?'Save changes':'Create product'}</button></div></div>
      </form>
    </AdminModal>}
  </div>;
}
