import { useCallback, useEffect, useMemo, useState } from 'react';
import { RiAddLine, RiDeleteBinLine, RiEditLine, RiSearchLine, RiCloseLine, RiStarFill } from '@remixicon/react';
import { adminService, itemsOfList } from '../../services/admin';
import { useToast } from '../../context/ToastContext';
import { formatMoney } from '../../utils/format';
import { ErrorState, Spinner } from '../../components/ui/States';
import AdminModal from './Modal';

const PAGE_SIZE=100, MAX_IMAGES=10;
const blank={name:'',slug:'',sku:'',category_id:'',price:'',compare_price:'',stock:'0',low_stock_threshold:'10',short_description:'',description:'',image_url:'',is_active:true,images:[]};
const toForm=(p)=>{const images=Array.isArray(p.images)?p.images.filter(Boolean):(p.image_url?[p.image_url]:[]);return {...blank,name:p.name||'',slug:p.slug||'',sku:p.sku||'',category_id:p.category_id||'',price:p.price!=null?String(p.price):'',compare_price:p.compare_price!=null?String(p.compare_price):'',stock:p.stock!=null?String(p.stock):'0',low_stock_threshold:p.low_stock_threshold!=null?String(p.low_stock_threshold):'10',short_description:p.short_description||'',description:p.description||'',image_url:images[0]||'',is_active:p.is_active!==false,images};};

export default function ProductsPanel({ capabilities={} }){
 const canCreate=capabilities.productCreate===true;const canUpdate=capabilities.productUpdate===true;const canDelete=capabilities.productDelete===true;const canManageImages=canUpdate;
 const {toast}=useToast();const [items,setItems]=useState(null);const [categories,setCategories]=useState([]);const [error,setError]=useState('');const [search,setSearch]=useState('');const [catFilter,setCatFilter]=useState('');const [editing,setEditing]=useState(false);const [editingId,setEditingId]=useState(null);const [form,setForm]=useState(blank);const [saving,setSaving]=useState(false);const [busyId,setBusyId]=useState(null);const [selectedFiles,setSelectedFiles]=useState([]);const [deletingImage,setDeletingImage]=useState(null);const [primaryBusy,setPrimaryBusy]=useState(null);
 const load=useCallback(async()=>{setError('');try{const[p,c]=await Promise.all([adminService.listProducts({page:1,page_size:PAGE_SIZE}),adminService.categories()]);setItems(itemsOfList(p));setCategories(itemsOfList(c));}catch(e){setError(e.message||'Unable to load products.')}},[]);useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return (items||[]).filter(p=>(!catFilter||String(p.category_id||p.category)===String(catFilter))&&(!q||[p.name,p.slug,p.sku].some(v=>String(v||'').toLowerCase().includes(q))))},[items,search,catFilter]);
 const openCreate=()=>{if(!canCreate)return;setEditingId(null);setForm({...blank});setSelectedFiles([]);setEditing(true)};const openEdit=(p)=>{if(!canUpdate)return;setEditingId(p.id);setForm(toForm(p));setSelectedFiles([]);setEditing(true)};
 const selectFiles=(e)=>{if(!canManageImages)return;const incoming=Array.from(e.target.files||[]);if(!incoming.length)return;if(incoming.some(f=>!f.type.startsWith('image/')))return toast.error('Please choose image files only.');if(incoming.some(f=>f.size>2*1024*1024))return toast.error('Each image must be 2 MB or smaller.');if(form.images.length+selectedFiles.length+incoming.length>MAX_IMAGES)return toast.error(`Maximum ${MAX_IMAGES} images per product.`);setSelectedFiles(v=>[...v,...incoming]);e.target.value=''};
 const removeImage=async(index)=>{if(!editingId||!canManageImages)return;setDeletingImage(index);try{const r=await adminService.deleteProductImage(editingId,index);const images=Array.isArray(r?.images)?r.images:form.images.filter((_,i)=>i!==index);setForm(v=>({...v,images,image_url:images[0]||''}));toast.success('Image removed.')}catch(e){toast.error(e.message||'Unable to remove image.')}finally{setDeletingImage(null)}};
 const setPrimary=async(index)=>{if(!editingId||index===0||!canManageImages)return;setPrimaryBusy(index);try{const ordered=[form.images[index],...form.images.filter((_,i)=>i!==index)];const r=await adminService.reorderProductImages(editingId,ordered);const images=Array.isArray(r?.images)?r.images:ordered;setForm(v=>({...v,images,image_url:images[0]||''}));toast.success('Primary image updated.')}catch(e){toast.error(e.message||'Unable to set primary image.')}finally{setPrimaryBusy(null)}};
 const validate=()=>{if(form.name.trim().length<2)return'Name must be at least 2 characters.';if(!/^[a-z0-9-]+$/.test(form.slug.trim().toLowerCase()))return'Slug can only contain lowercase letters, numbers and dashes.';if(!(Number(form.price)>0))return'Price must be greater than zero.';if(form.compare_price!==''&&Number(form.compare_price)<=Number(form.price))return'Compare-at price must be greater than the price.';return null};
 const save=async(e)=>{e.preventDefault();if(editingId&&!canUpdate)return;if(!editingId&&!canCreate)return;const problem=validate();if(problem)return toast.error(problem);setSaving(true);try{const images=form.images.filter(Boolean);const base={category_id:form.category_id||undefined,image_url:images[0]||form.image_url.trim()||undefined,images,short_description:form.short_description.trim()||undefined,description:form.description.trim()||undefined,is_active:form.is_active,price:Number(form.price),compare_price:form.compare_price===''?undefined:Number(form.compare_price),stock:Number(form.stock)||0,low_stock_threshold:Number(form.low_stock_threshold)||0};if(editingId){await adminService.updateProduct(editingId,base);if(selectedFiles.length)await adminService.uploadProductImages(editingId,selectedFiles);toast.success('Product updated.')}else{const data={...base,name:form.name.trim(),slug:form.slug.trim().toLowerCase(),sku:form.sku.trim()||undefined};if(selectedFiles.length)await adminService.createProductWithImages(data,selectedFiles);else await adminService.createProduct(data);toast.success('Product created.')}setEditing(false);setSelectedFiles([]);await load()}catch(e){toast.error(e.message||'Unable to save product.')}finally{setSaving(false)}};
 const remove=async(p)=>{if(!canDelete)return;if(!window.confirm(`Delete \"${p.name}\"? This cannot be undone.`))return;setBusyId(p.id);try{await adminService.deleteProduct(p.id);toast.success('Product deleted.');await load()}catch(e){toast.error(e.message||'Unable to delete product.')}finally{setBusyId(null)}};
 if(error)return <ErrorState message={error} onRetry={load}/>;if(items===null)return <Spinner label="Loading products…"/>;
 return <div><div className="admin-head"><div><h1>Products</h1><p className="admin-sub">{filtered.length} of {items.length} shown.</p></div>{canCreate&&<button className="btn btn-sm" onClick={openCreate}><RiAddLine size={16}/> Add product</button>}</div><div className="admin-table-wrap"><div className="admin-toolbar"><label className="admin-search"><RiSearchLine size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products…"/></label><select className="admin-select" value={catFilter} onChange={e=>setCatFilter(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.id||c.slug} value={c.id||c.slug}>{c.name}</option>)}</select></div>{filtered.length===0?<div className="admin-empty">No products match.</div>:<table className="admin-table"><thead><tr><th>Product</th><th>SKU</th><th>Price</th><th>Stock</th><th>Category</th><th>Status</th>{(canUpdate||canDelete)&&<th/>}</tr></thead><tbody>{filtered.map(p=>{const cat=categories.find(c=>c.id===p.category_id);return <tr key={p.id}><td><div className="td-strong">{p.name}</div><div className="td-dim">{p.slug}</div></td><td className="td-dim">{p.sku||'—'}</td><td className="td-gold">{formatMoney(Number(p.price)||0)}</td><td>{p.stock}</td><td className="td-dim">{cat?.name||'—'}</td><td>{p.is_active===false?<span className="admin-pill pill-danger">Inactive</span>:<span className="admin-pill pill-success">Active</span>}</td>{(canUpdate||canDelete)&&<td><div className="btn-row">{canUpdate&&<button className="btn btn-quiet btn-sm" onClick={()=>openEdit(p)}><RiEditLine size={14}/> Edit</button>}{canDelete&&<button className="btn btn-quiet btn-sm" onClick={()=>remove(p)} disabled={busyId===p.id}><RiDeleteBinLine size={14}/></button>}</div></td>}</tr>})}</tbody></table>}</div>
 {editing&&<AdminModal title={editingId?'Edit product':'Add product'} sub="Primary image is the first image used for cards, SEO and social previews." onClose={()=>setEditing(false)}><form onSubmit={save}><div className="field-grid"><div className="field"><label>Name *</label><input required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></div><div className="field"><label>Slug *</label><input required disabled={!!editingId} value={form.slug} onChange={e=>setForm(v=>({...v,slug:e.target.value}))}/></div></div><div className="field-grid"><div className="field"><label>Price (₹) *</label><input required type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm(v=>({...v,price:e.target.value}))}/></div><div className="field"><label>Compare-at price</label><input type="number" min="0" step="0.01" value={form.compare_price} onChange={e=>setForm(v=>({...v,compare_price:e.target.value}))}/></div></div><div className="field-grid"><div className="field"><label>Stock</label><input type="number" min="0" value={form.stock} onChange={e=>setForm(v=>({...v,stock:e.target.value}))}/></div><div className="field"><label>Low-stock threshold</label><input type="number" min="0" value={form.low_stock_threshold} onChange={e=>setForm(v=>({...v,low_stock_threshold:e.target.value}))}/></div></div><div className="field-grid"><div className="field"><label>Category</label><select value={form.category_id} onChange={e=>setForm(v=>({...v,category_id:e.target.value}))}><option value="">None</option>{categories.map(c=><option key={c.id||c.slug} value={c.id||c.slug}>{c.name}</option>)}</select></div><div className="field"><label>SKU</label><input value={form.sku} onChange={e=>setForm(v=>({...v,sku:e.target.value}))}/></div></div>
 <div className="field"><label>Product images <span className="field-hint-inline">{form.images.length+selectedFiles.length}/{MAX_IMAGES}</span></label><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={selectFiles} disabled={!canManageImages||form.images.length+selectedFiles.length>=MAX_IMAGES}/><small className="field-hint">The first image is the primary image. Use “Set primary” to change it. Up to {MAX_IMAGES} images.</small>{form.images.length>0&&<div className="admin-image-grid">{form.images.map((src,index)=><div className={`admin-image-item ${index===0?'is-primary':''}`} key={`${src}-${index}`}><img src={src} alt={`Product image ${index+1}`}/><span className="admin-image-index">{index===0?<><RiStarFill size={12}/> Primary</>:index+1}</span><div className="admin-image-actions">{index!==0&&editingId&&canManageImages&&<button type="button" className="btn btn-quiet btn-sm" disabled={primaryBusy===index} onClick={()=>setPrimary(index)}>{primaryBusy===index?'Saving…':'Set primary'}</button>}{editingId&&canManageImages&&<button type="button" className="icon-btn" disabled={deletingImage===index} onClick={()=>removeImage(index)} aria-label="Remove image"><RiCloseLine size={14}/></button>}</div></div>)}</div>}{selectedFiles.length>0&&<div className="selected-image-list">{selectedFiles.map((f,i)=><div className="selected-image-row" key={`${f.name}-${i}`}><span>{f.name}</span></div>)}</div>}</div>
 <div className="field"><label>Short description</label><input value={form.short_description} onChange={e=>setForm(v=>({...v,short_description:e.target.value}))}/></div><div className="field"><label>Description</label><textarea value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></div><label className="check-line"><input type="checkbox" checked={form.is_active} onChange={e=>setForm(v=>({...v,is_active:e.target.checked}))}/> Active</label><button className="btn btn-block" disabled={saving}>{saving?'Saving…':editingId?'Save changes':'Create product'}</button></form></AdminModal>}</div>;
}
